# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_prbac.fields
import django_prbac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Assignment from parameters (strings) to values (any JSON-compatible value)')),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='The formal slug for this role, which should be unique', max_length=256, unique=True)),
                ('name', models.CharField(help_text='The friendly name for this role to present to users; this need not be unique.', max_length=256)),
                ('description', models.TextField(blank=True, default='', help_text='A long-form description of the intended semantics of this role.')),
                ('parameters', django_prbac.fields.StringSetField(blank=True, default=set, help_text='A set of strings which are the parameters for this role. Entered as a JSON list.')),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='django_prbac.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prbac_role', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
        migrations.AddField(
            model_name='grant',
            name='from_role',
            field=models.ForeignKey(help_text='The sub-role begin granted membership or permission', on_delete=django.db.models.deletion.CASCADE, related_name='memberships_granted', to='django_prbac.Role'),
        ),
        migrations.AddField(
            model_name='grant',
            name='to_role',
            field=models.ForeignKey(help_text='The super-role or permission being given', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='django_prbac.Role'),
        ),
    ]
